title:             Jason Lim
email:             jasonjklim@gmail.com
description:       Data Scientist & Data Analyst
author:            Jason Lim
baseurl:           ""
url:               "http://jasonjklim.github.io"

# Social Profiles

github_username:   jasonjklim


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
